# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edaa8662ed4ea10f8119609682551c75469305d237457e251a79868a0f3cc7b005c4faf148ea0136dcdf0a81e8b47912da1b056519a2f7fc1436724f7dc02c62

test:
  secret_key_base: a3c7cf8b16ebd844191b4ac1927da6bb96789270542b02d6e7a2f704ab286dfa071419446158761815c6c066d99b2bf4004e114022b83726a1009e5e2195f4c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
